import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getTitleForHome } from "../lib/api";

export default function Home({ title, preview }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{title}</h1>
      </main>

      <footer className={styles.footer}>
        <p>cms-next-cdk</p>
      </footer>
    </div>
  )
}

export async function getStaticProps({ preview = null }) {
  const title = await getTitleForHome(preview) || []
  return {
    props: { title, preview }
  }
}
